f1=open("file_2.txt","w" or "x")
f1.write("happy birthday ")
f1.close()
f2=open("file_1.txt","w" or "x")
f2.write("birtday happy")
f2.close()
p=open("file_1.txt","r")
q=open("file_2.txt","r")
x=p.read()
y=q.read()
f3=open("file_4.txt","x" or "r+")
f3.write(x+" "+y)
f3.close()
f2.close()
f1.close()
